export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PRISMA_UNKNOWN_ERROR: 'PRISMA_UNKNOWN_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Validation
  INVALID_INPUT: 'INVALID_INPUT',

  // Database
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Movies
  MOVIE_ALREADY_IN_WATCHLIST: 'MOVIE_ALREADY_IN_WATCHLIST',
  MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',

  // Watchlist
  WATCHLIST_ITEM_NOT_FOUND: 'WATCHLIST_ITEM_NOT_FOUND',

  // Prisma (dev-only)
  PRISMA_VALIDATION_ERROR: 'PRISMA_VALIDATION_ERROR',
};
